### PR TITLE
fix requirements.txt and minor update for frontend

### LINKED ISSUE #62: Event Button
## Task
For the Event story, I would need to add a button in order to create an event.

## Link to story
#5

### PR DESCRIPTION
**Pull request by leroynle**

### CODE REVIEW

**Comment by ngducn** [comment]
Can you commit only the coding part that we need to review? This PR has 338 files change and we cannot review them all. 
I think I have to reject this one and have you create a new PR.

**Review by ngducn — CHANGES_REQUESTED** [review]
Please make a new PR with only important files. 338 files changed are too much to look at.

**Comment by leroynle** [comment]
I removed all unnecessary files from the previous PR. Please review it

**Review by ngducn — APPROVED** [review]
The amount of file changes is from the change of packages used in backend. Consider putting the site-packages into .gitignore. 

Other than that, looks good to me!

**Pull request merged**
